### ISSUE TITLE
clarify difference between gas used and gas charged

### ISSUE THREAD

**Issue by canhtrinh** [axelarnetwork/axelarscan-ui#11]
**Is your feature request related to a problem? Please describe.**
unclear what the difference is. 

**Describe the solution you'd like**
used is the true cost. charged is the gas paid - gas refund. due to subsidies gas used can be higher than gas charged for some chains. we should probably add a tooltip, and move the used value in a details section

**Describe alternatives you've considered**

**Additional context**

**Comment by pjenviri** [comment]
added the tooltip: https://axelarscan-ui-rebuild.vercel.app/gmp/0x923df320c255d17676f837debc0415791104edc155f1b244b7f1b21e119ec883-18
