### ISSUE TITLE
Change axelarscan.io link to "token info guides"

### ISSUE THREAD

**Issue by galenmoore** [axelarnetwork/axelarscan-ui#12]
Please change the link to "AXL token info guides" at the top of axelarscan.io homepage. We've consolidated most of the information into one blog post: 

Link text: How to stake AXL
Link url: https://www.axelar.network/blog/how-to-stake-the-axl-token-on-the-axelar-network

**Comment by pjenviri** [comment]
@galenmoore, could you suggest where to add the link on the homepage of the refactored [version](https://axelarscan-ui-rebuild.vercel.app)?

**Comment by galenmoore** [comment]
Ah, I see this has been removed in refactored version - my bad. 

/validators would be a good place, if there is room on that page. It looks like it could fit on the same section as "List of active validators in Axelar Network with the latest 10K blocks performance." - either to the right or just below that line.

**Comment by pjenviri** [comment]
thank you @galenmoore, the link has been added to the Validators page: https://axelarscan-ui-rebuild.vercel.app/validators.
