### ISSUE TITLE
Footer covers bottom edge of daisywheel graphic / scroll to view transactions? 

### ISSUE THREAD

**Issue by galenmoore** [axelarnetwork/axelarscan-ui#13]
Hi - The footer on axelarscan.io covers the bottom edge of the daisywheel graphic. This is happening on 13" Macbook with both Safari and Brave browsers. It may create the expectation that the page will scroll, which isn't happening. 

Or ... is the page intended to scroll? Some users may expect to scroll down to see a list of the latest transactions and/or blocks. If that's there I wasn't able to scroll down through it on the browsers I mentioned.

**Comment by pjenviri** [comment]
hey @galenmoore, we have improved how pagination works on the UI in the [refactored version](https://axelarscan-ui-rebuild.vercel.app/transactions). It removes the confusing daisywheel loading graphic.
