### ISSUE TITLE
Axelarscan footer needs updating

### ISSUE THREAD

**Issue by galenmoore** [axelarnetwork/axelarscan-ui#14]
Please update Axelarscan.io footer. It should have these elements, same as axelar.network footer: 

COPYRIGHT © 2024 AXELAR FOUNDATION. ALL RIGHTS RESERVED.

[PRIVACY POLICY](https://www.axelar.network/privacy-policy)

[TERMS OF USE](https://www.axelar.network/terms-of-use)

**Comment by pjenviri** [comment]
updated: https://axelarscan-ui-rebuild.vercel.app/
