### ISSUE TITLE
For interchainTransfer show destination address and blockchain logo

### ISSUE THREAD

**Issue by SKYBITDev3** [axelarnetwork/axelarscan-ui#2]
In the interface of an interchainTransfer, the last step shown is "Executed" with links to the addresses of the Axelar Relayer and Interchain Token Service on destination blockchain.

It should show the address (with link) of the final recipient of the assets in the final step, just as you show the source address in the first step.

**Comment by pjenviri** [comment]
Updated to display destination address on the Executed step in this pr: https://github.com/CoinHippo-Labs/axelarscan-ui/pull/83.
