### ISSUE TITLE
Pay Gas Button Errors For Base

### ISSUE THREAD

**Issue by benjamin852** [axelarnetwork/axelarscan-ui#26]
For this underfunded [tx](https://axelarscan.io/gmp/0x4354d84f86a7dc7c86509c5104bcfa94324b1e7a61d006f5a05f1a7ed57d8ab2) the user is unable to add gas from axerlascan

Axelarscan returns the error 
```
{success: false, error: "Couldn't query the gas price"}
```

Note: I was able to add gas just fine for CELO the other day so I am assuming this is a BASE issue.

**Comment by pjenviri** [comment]
@benjamin852 , can you try again? The issue should be resolved, but please help confirming it. 

Previously, axelarscan didn't automatically query the gas limit for each contract for the "unpaid" TX when user didn't specify the gas limit information; it only supported querying for the insufficient gas paid TX (more info in this discussion [thread](https://interoplabs.slack.com/archives/C035KBHNP8A/p1714474061942249?thread_ts=1714046774.822279&cid=C035KBHNP8A)). So we updated it to be able to handle the case as well.

**Comment by benjamin852** [comment]
Great! I actually do not have any funds on Base mainnet :P So it throws an insufficient funds error for me before popping my metamask.

**Comment by pjenviri** [comment]
I paid gas to the tx. it worked. https://axelarscan.io/gmp/0x4354d84f86a7dc7c86509c5104bcfa94324b1e7a61d006f5a05f1a7ed57d8ab2. closing the ticket.
