### ISSUE TITLE
"load more" at the bottom should take you to the new page

### ISSUE THREAD

**Issue by StephenFluin** [axelarnetwork/axelarscan-ui#3]
Currently when I hit "load more" in the bottom right corner of https://testnet.axelarscan.io/gmp/search, it loads another page, but then I have to click to visit that page. It should automatically take me there.

**Comment by pjenviri** [comment]
[Updated](https://github.com/axelarnetwork/axelarscan-ui/commit/c594a8a719025ea3dc0a23e4cd552d1d4f1d0584).
