### ISSUE TITLE
Misc GMP view issues

### ISSUE THREAD

**Issue by milapsheth** [axelarnetwork/axelarscan-ui#31]
Some misc issues with GMP views:
1. Distinguish source address and destination contract with separate rows in GMP [view](https://axelarscan.io/gmp/0x67886eca97d3d6d5a88080cc7b70a168ad1efb2d4af59bfde6cde8dbf0562bbe-4)
2. Change `Source` -> `Sender/User` on the GMP [page](https://axelarscan.io/gmp/search)
3. For `X -> Cosmos`, [routing](https://axelarscan.io/gmp/0x8b35acf9ab3ff3edaf99d2f5ccfb89f7b6b654be5f5e945de514698c9dbab851-3) can be shown as a separate step, maybe call it Approved vs Executed perhaps. The Executed step can link to the IBC ack as well.
4. Maybe `Gas Paid`, `Gas Used`, and `Base Fee` can be under `See More`? Users mostly care about `Gas Charged`
5. Block height column for each tx in the GMP [view](https://axelarscan.io/gmp/0xc95949b6c90fbc87b62e99fa23721e3eb137e03859bcbedad86218f8d428e65c-7) doesn’t seem very useful?
6. `Gas Refunded` -> `Excess Gas Refunded` in the GMP view
7. `Final User Recipient` -> `Squid Recipient` maybe?
8. Maybe add `ITS Recipient` similarly

**Comment by nrsirapop** [comment]
5. useful for support/debug/recovery
