### ISSUE TITLE
TVL scrolling breaks background colour

### ISSUE THREAD

**Issue by milapsheth** [axelarnetwork/axelarscan-ui#36]
When scrolling horizontally at the top of the TVL page, a white header appears

<img width="1712" alt="Screenshot 2024-05-18 at 6 19 51 PM" src="https://github.com/axelarnetwork/axelarscan-ui/assets/14846413/0dfdded1-9b38-46ce-a8db-3196be846509">

**Comment by pjenviri** [comment]
fixed.
<img width="1440" alt="Screenshot 2567-05-22 at 17 33 34" src="https://github.com/axelarnetwork/axelarscan-ui/assets/87146398/33b4fab3-1371-462e-9b07-96ea84ed12bf">
