### ISSUE TITLE
feat: display pre-filled search GMP filter values in alphabetical order

### ISSUE THREAD

**Issue by kalidax** [axelarnetwork/axelarscan-ui#52]
**Is your feature request related to a problem? Please describe.**

Pre-filled search GMP filter values are not displayed in alphabetical order here https://axelarscan.io/gmp/search.

**Describe the solution you'd like**

 Implement the logic to display these values (for assets, source chains, destination chains) in alphabetical order here: https://axelarscan.io/gmp/search.

**Describe alternatives you've considered**

 Implement the logic to display assets, source chains, destination chains in alphabetical order here: https://axelarscan.io/gmp/search.

**Additional context**
![image](https://github.com/axelarnetwork/axelarscan-ui/assets/97290719/bf6c8a79-fdfa-4f98-94e4-68a90c56d823)
![image](https://github.com/axelarnetwork/axelarscan-ui/assets/97290719/3875775b-e54e-404e-a211-f68a8589f4cf)

**Comment by pjenviri** [comment]
updated
