### ISSUE TITLE
Social share image uses old logo

### ISSUE THREAD

**Issue by canhtrinh** [axelarnetwork/axelarscan-ui#8]
GM. Looks like the social share image at <http://axelarscan.io/interchain|axelarscan.io/interchain> is still has the old, old Axelar logo. Or, could this be a caching issue in Telegram?

[Slack Message](https://interoplabs.slack.com/archives/C035KBHNP8A/p1712927659568499)

**Comment by nrsirapop** [comment]
updated the preview via @webpagebot telegram bot.
